# Generated by Django 4.2.4 on 2025-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField(default=None)),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_answer', models.BooleanField()),
                ('content', models.TextField(default=None)),
            ],
        ),
    ]
