# Generated by Django 4.2.4 on 2025-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='images',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
