# Generated by Django 4.2.4 on 2025-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inquiry_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='num_insights',
            field=models.IntegerField(default=1),
        ),
    ]
