# Generated by Django 4.2.4 on 2025-01-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inquiry_num_insights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='num_insights',
            new_name='rounds',
        ),
    ]
