# Generated by Django 5.1.5 on 2025-01-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_num_insights_inquiry_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='images',
        ),
    ]
